export const BODY_DATA_TYPES = {
    PAYMENT : 'PAYMENT',
    DELIVERY: 'DELIVERY',
    WARRANTY: 'WARRANTY',
    PERSONAL_AREA: 'PERSONAL_AREA',
    CARD: 'CARD',
    RESULT_BY_SEARCH: 'RESULT_BY_SEARCH',
    SEARCH_BY_CAR: 'SEARCH_BY_CAR',
};